# Generated by Django 4.2 on 2023-05-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('duration', models.DateTimeField()),
                ('uploadfile', models.FileField(upload_to='ps2')),
                ('uploadtime', models.TimeField(verbose_name='')),
            ],
        ),
    ]
